import type { ScreenKey, WorkflowDefinition } from "./types";

export const workflowDefinitions: WorkflowDefinition[] = [
  {
    key: "floorplan",
    screen: "floorplan",
    title: "平面图可视化",
    titleEn: "Floor Plan Visualization",
    shortTitle: "平面图",
    shortTitleEn: "Floor Plan",
    uploadTitle: "上传平面图或草图",
    uploadTitleEn: "Upload a floor plan or sketch",
    assetType: "floorplan",
    source: "floorplan",
    module: "floorplan",
    taskType: "provider_floorplan_render",
    capability: "image_to_image",
    defaultPrompt: "请保留墙体、门窗、房间关系，把上传图转换成清晰的室内设计展示平面图。",
    defaultPromptEn: "Preserve walls, doors, windows, and room relationships while converting the upload into a clear interior presentation floor plan.",
    defaultStyle: "现代暖调",
  },
  {
    key: "singleRoom",
    screen: "singleRoom",
    title: "单房间方案板",
    titleEn: "Single-Room Board",
    shortTitle: "单房间",
    shortTitleEn: "Single Room",
    uploadTitle: "上传单张房间图",
    uploadTitleEn: "Upload one room image",
    assetType: "render_input",
    source: "single_room_board",
    module: "single_room_board",
    taskType: "provider_single_room_board",
    capability: "image_to_image",
    defaultPrompt: "根据上传房间图生成一张软装方案板，包含材质、色彩、家具清单和报价摘要视觉区。",
    defaultPromptEn: "Create a furnishing board from the uploaded room image with materials, colors, a furniture list, and a budget summary.",
    defaultStyle: "柔和极简",
  },
  {
    key: "multiRoom",
    screen: "multiRoom",
    title: "多房间方案板",
    titleEn: "Multi-Room Board",
    shortTitle: "多房间",
    shortTitleEn: "Multi Room",
    uploadTitle: "上传多张房间图",
    uploadTitleEn: "Upload multiple room images",
    assetType: "render_input",
    source: "multi_room_board",
    module: "multi_room_board",
    taskType: "provider_multi_room_board",
    capability: "image_to_image",
    defaultPrompt: "根据全部上传房间图生成整屋综合方案板，保留原图配色、家具轮廓、材质和灯光氛围，并输出预算汇总。",
    defaultPromptEn: "Create a whole-home board from all uploaded room images, preserving colors, furniture forms, materials, and lighting while including a budget summary.",
    defaultStyle: "整屋统一现代",
    requiresMultiple: true,
  },
  {
    key: "spaceRender",
    screen: "spaceRender",
    title: "空间渲染",
    titleEn: "Space Rendering",
    shortTitle: "空间渲染",
    shortTitleEn: "Rendering",
    uploadTitle: "上传空间图 / SU 截图",
    uploadTitleEn: "Upload a space image or SU screenshot",
    assetType: "space_input",
    source: "space_render",
    module: "space_render",
    taskType: "provider_space_render",
    capability: "image_to_image",
    defaultPrompt: "保留上传图片主体结构、窗洞、墙地面关系和构图，生成真实感室内精修效果图。",
    defaultPromptEn: "Preserve the source structure, openings, wall-floor relationships, and composition while creating a photorealistic refined interior render.",
    defaultStyle: "现代自然",
  },
  {
    key: "customTasks",
    screen: "customTasks",
    title: "自定义任务",
    titleEn: "Custom Task",
    shortTitle: "自定义",
    shortTitleEn: "Custom",
    uploadTitle: "上传参考图",
    uploadTitleEn: "Upload reference images",
    assetType: "reference_image",
    source: "custom_task",
    module: "custom_tasks",
    taskType: "provider_custom_task",
    capability: "image_to_image",
    defaultPrompt: "根据上传参考图和当前任务要求生成一张可归档的室内设计输出。",
    defaultPromptEn: "Create an archivable interior design output from the uploaded references and current task requirements.",
    defaultStyle: "自定义",
  },
];

export const tabs: Array<{ key: ScreenKey; label: string }> = [
  { key: "projects", label: "项目" },
  { key: "floorplan", label: "平面图" },
  { key: "singleRoom", label: "单房间" },
  { key: "multiRoom", label: "多房间" },
  { key: "spaceRender", label: "空间渲染" },
  { key: "customTasks", label: "自定义" },
  { key: "prompts", label: "提示词" },
  { key: "models", label: "模型" },
  { key: "archive", label: "回看" },
];

export const aspectRatios = ["16:9", "4:3", "1:1", "3:4", "9:16"];

export const roomTypes = ["客厅", "餐厅", "卧室", "厨房", "卫生间", "书房", "展厅", "自定义"];

export const designStyles = ["现代暖调", "柔和极简", "侘寂日式", "酒店轻奢", "新中式", "自然现代", "自定义"];

export const materialSuggestions = ["胡桃木", "洞石", "羊羔绒", "亚麻", "黄铜", "微水泥", "橡木"];

export const mobileImageRoutePresets = [
  {
    key: "openai-direct",
    provider_id: "openai",
    providerLabel: "OpenAI 原生",
    providerLabelEn: "OpenAI Native",
    model_name: "gpt-image-2",
    display_name: "GPT Image 2",
    routing_mode: "direct_api",
    compatibility_mode: "native",
    api_key_name: "OPENAI_API_KEY",
    base_url: "https://api.openai.com/v1",
    endpoint: "/images/generations / /images/edits",
    priority: 20,
  },
  {
    key: "openai-relay",
    provider_id: "openai",
    providerLabel: "OpenAI 中转",
    providerLabelEn: "OpenAI Relay",
    model_name: "gpt-image-2",
    display_name: "GPT Image 2 Relay",
    routing_mode: "relay_base_url",
    compatibility_mode: "openai_compatible",
    api_key_name: "OPENAI_RELAY_API_KEY",
    base_url: "",
    endpoint: "/images/generations / /images/edits",
    priority: 21,
  },
  {
    key: "gemini-direct",
    provider_id: "google_gemini",
    providerLabel: "Google Gemini 原生",
    providerLabelEn: "Google Gemini Native",
    model_name: "gemini-2.5-flash-image",
    display_name: "Gemini 2.5 Flash Image (Nano Banana)",
    routing_mode: "direct_api",
    compatibility_mode: "native",
    api_key_name: "GEMINI_API_KEY",
    base_url: "https://generativelanguage.googleapis.com/v1beta",
    endpoint: "/models/gemini-2.5-flash-image:generateContent",
    priority: 30,
  },
  {
    key: "gemini-pro-direct",
    provider_id: "google_gemini",
    providerLabel: "Google Gemini 原生",
    providerLabelEn: "Google Gemini Native",
    model_name: "gemini-3-pro-image-preview",
    display_name: "Gemini 3 Pro Image Preview (Nano Banana Pro)",
    routing_mode: "direct_api",
    compatibility_mode: "native",
    api_key_name: "GEMINI_API_KEY",
    base_url: "https://generativelanguage.googleapis.com/v1beta",
    endpoint: "/models/gemini-3-pro-image-preview:generateContent",
    priority: 32,
  },
  {
    key: "gemini-flash2-direct",
    provider_id: "google_gemini",
    providerLabel: "Google Gemini 原生",
    providerLabelEn: "Google Gemini Native",
    model_name: "gemini-3.1-flash-image-preview",
    display_name: "Gemini 3.1 Flash Image Preview (Nano Banana 2)",
    routing_mode: "direct_api",
    compatibility_mode: "native",
    api_key_name: "GEMINI_API_KEY",
    base_url: "https://generativelanguage.googleapis.com/v1beta",
    endpoint: "/models/gemini-3.1-flash-image-preview:generateContent",
    priority: 33,
  },
] as const;

export const mobileExtractionRoutePresets = [
  {
    key: "glm-direct",
    display_name_en: "GLM-4.5V Multimodal Extraction",
    provider_id: "zhipu_glm",
    providerLabel: "智谱 GLM（中国大陆）",
    providerLabelEn: "Zhipu GLM (Mainland China)",
    model_name: "glm-4.5v",
    display_name: "GLM-4.5V 多模态提取",
    routing_mode: "direct_api",
    compatibility_mode: "native",
    api_key_name: "ZHIPU_API_KEY",
    base_url: "https://open.bigmodel.cn/api/paas/v4",
    endpoint: "/chat/completions",
    priority: 40,
  },
  {
    key: "glm-international-direct",
    display_name_en: "GLM-4.5V Multimodal Extraction",
    provider_id: "zai_glm",
    providerLabel: "Z.AI GLM（国际/海外）",
    providerLabelEn: "Z.AI GLM (International)",
    model_name: "glm-4.5v",
    display_name: "GLM-4.5V 多模态提取",
    routing_mode: "direct_api",
    compatibility_mode: "native",
    api_key_name: "ZAI_API_KEY",
    base_url: "https://api.z.ai/api/paas/v4",
    endpoint: "/chat/completions",
    priority: 41,
  },
] as const;

export function isGlmExtractionProvider(providerId: string): boolean {
  return providerId === "zhipu_glm" || providerId === "zai_glm";
}

export const interiorPromptPresets = [
  {
    name: "空间图精修真实感",
    nameEn: "Photorealistic Space Refinement",
    module: "space_render",
    userPrompt: "基于上传的空间照片或 SU 截图生成真实感室内效果图。必须保留原始空间结构、墙体位置、门窗洞口、顶面高度、地面边界、主要家具尺度和相机视角；优化材质、灯光、软装和氛围。风格为 {style}，空间类型为 {room_type}，材质关键词为 {material_keywords}。输出应像专业室内摄影，光线自然，细节清晰，可直接用于客户沟通。",
    userPromptEn: "Create a photorealistic interior rendering from the uploaded room photo or SketchUp screenshot. Preserve the original structure, wall positions, door and window openings, ceiling height, floor boundaries, main furniture scale, and camera view. Refine materials, lighting, furnishings, and atmosphere. Style: {style}; room type: {room_type}; material keywords: {material_keywords}. The result should resemble professional interior photography with natural light and clear detail suitable for client presentation.",
    negativePrompt: "改变户型结构、移动门窗、墙体变形、家具比例错误、过度豪华、画面拥挤、低清晰度、文字水印、畸变、脏乱、假植物过多",
    negativePromptEn: "changed floor-plan structure, moved doors or windows, distorted walls, incorrect furniture scale, excessive luxury, clutter, low resolution, text, watermark, distortion, mess, excessive artificial plants",
  },
  {
    name: "毛坯 / 白模转精装",
    nameEn: "Shell or White Model to Finished Interior",
    module: "space_render",
    userPrompt: "将上传的毛坯、白模或 SketchUp 截图转为完成度高的精装室内渲染图。保持原始空间体块、开窗、梁柱、墙地顶关系和透视角度不变；补充真实材质、灯带、家具、窗帘、地毯、装饰画和绿植。风格为 {style}，材质为 {material_keywords}，整体干净、克制、有交付质感。",
    userPromptEn: "Transform the uploaded unfinished room, white model, or SketchUp screenshot into a polished interior rendering. Preserve the original massing, openings, beams, columns, wall-floor-ceiling relationships, and perspective. Add realistic materials, integrated lighting, furniture, curtains, rugs, artwork, and plants. Style: {style}; materials: {material_keywords}. Keep the result clean, restrained, and presentation-ready.",
    negativePrompt: "拆改结构、窗户消失、透视错误、比例失真、材质廉价、过曝、过暗、模型感、卡通感、文字和 logo",
    negativePromptEn: "structural changes, missing windows, incorrect perspective, distorted proportions, cheap materials, overexposure, underexposure, obvious 3D model appearance, cartoon style, text, logo",
  },
  {
    name: "单房间软装方案板",
    nameEn: "Single-room Furnishing Board",
    module: "single_room_board",
    userPrompt: "根据上传房间图生成一张室内软装方案板。保留房间主色调和空间关系，提炼 {style} 风格方向，展示主视觉效果、材质样板、家具建议、灯具建议、色彩搭配和预算提示。空间类型为 {room_type}，材质关键词为 {material_keywords}。版面应清晰、留白充足、适合给客户快速确认方向。",
    userPromptEn: "Create an interior furnishing board from the uploaded room image. Preserve the room's primary color palette and spatial relationships. Develop a {style} direction and present a main visual, material samples, furniture suggestions, lighting suggestions, a color palette, and budget cues. Room type: {room_type}; material keywords: {material_keywords}. Use a clear layout with sufficient whitespace for quick client approval.",
    negativePrompt: "版面拥挤、文字不可读、价格胡编、图片重复、材质不一致、风格漂移、低清晰度",
    negativePromptEn: "crowded layout, unreadable text, invented pricing, duplicate images, inconsistent materials, style drift, low resolution",
  },
  {
    name: "平面图 2D/3D 可视化",
    nameEn: "2D/3D Floor-plan Visualization",
    module: "floorplan",
    userPrompt: "将上传的平面图、草图或黑白图转成清晰的室内设计展示图。必须保留墙体、门窗、房间关系、动线和开间进深比例；增强空间分区、家具布置、地面材质和色彩层级。输出为 {style} 风格，空间类型为 {room_type}，适合方案汇报。",
    userPromptEn: "Convert the uploaded floor plan, sketch, or monochrome drawing into a clear interior-design presentation image. Preserve walls, doors, windows, room relationships, circulation, and dimensional proportions. Enhance zoning, furniture layout, floor materials, and color hierarchy. Style: {style}; room type: {room_type}. The result should be suitable for a design presentation.",
    negativePrompt: "改变墙体、缺失门窗、房间关系错误、标注混乱、比例失真、文字乱码、低清晰度",
    negativePromptEn: "changed walls, missing doors or windows, incorrect room relationships, confusing annotations, distorted proportions, garbled text, low resolution",
  },
] as const;
