const labelMap: Record<string, string> = {
  dashboard: "工作台",
  projects: "项目",
  floorplan: "平面图",
  boards: "方案板",
  single_room_board: "单房间方案板",
  multi_room_board: "多房间方案板",
  space_render: "空间渲染",
  image_editing: "图片编辑",
  custom_tasks: "自定义任务",
  provider_floorplan_render: "平面图渲染",
  provider_space_render: "空间渲染",
  provider_single_room_board: "单房间方案板生成",
  provider_multi_room_board: "多房间方案板生成",
  provider_custom_task: "自定义任务生成",
  provider_test: "模型连接测试",
  provider_generation: "真实模型输出",
  board_preview_renderer: "方案板预览",
  render_output: "渲染输出",
  board_output: "方案板输出",
  provider_text_smoke_test: "文本连通性测试",
  extract_items: "提取元素",
  generate_space_render: "空间渲染",
  render_floorplan: "平面图渲染",
  queued: "排队中",
  running: "运行中",
  success: "成功",
  failed: "失败",
  cancelled: "已取消",
  active: "进行中",
  review: "复盘中",
  archived: "已归档",
  keep: "保留",
  replace: "替换",
  remove: "删除",
  undecided: "待定",
  Living: "客厅",
  Lounge: "休闲区",
  Room: "房间",
  "Living Room": "客厅",
  "Dining Room": "餐厅",
  Bedroom: "卧室",
  Kitchen: "厨房",
  Bathroom: "卫生间",
  "Home Office": "书房",
  Entryway: "玄关",
  Retail: "零售空间",
  Restaurant: "餐厅空间",
  "Hotel Lobby": "酒店大堂",
  Showroom: "展厅",
  Custom: "自定义",
  Modern: "现代",
  Minimal: "极简",
  "Soft Minimal": "柔和极简",
  Japandi: "侘寂日式",
  "Japandi Soft": "柔和侘寂",
  Scandinavian: "北欧",
  "Wabi-sabi": "侘寂",
  Contemporary: "当代",
  "Contemporary Luxury": "当代轻奢",
  "Modern Classic": "现代古典",
  "Mid-century Modern": "中古现代",
  Industrial: "工业风",
  "Warm Modern": "暖调现代",
  "Modern Warm": "现代暖调",
  "Organic Modern": "自然现代",
  Mediterranean: "地中海",
  "French Modern": "法式现代",
  "Art Deco": "装饰艺术",
  "New Chinese": "新中式",
  Zen: "禅意",
  "Hospitality Chic": "酒店风",
  "Retail Luxury": "零售轻奢",
  "Luxury Hospitality": "酒店轻奢",
  "Minimal Neutral": "中性极简",
  Daylight: "自然日光",
  "Golden Hour": "金色时刻",
  "Evening Glow": "傍晚暖光",
  "Studio Softbox": "影棚柔光",
  "Overcast Soft Light": "阴天柔光",
  "Night Ambient": "夜间氛围光",
  "Retail Spotlight": "零售重点照明",
  walnut: "胡桃木",
  travertine: "洞石",
  boucle: "羊羔绒",
  linen: "亚麻",
  brass: "黄铜",
  oak: "橡木",
  microcement: "微水泥",
  marble: "大理石",
  ivory: "象牙白",
  taupe: "灰褐色",
  greige: "灰米色",
  moss: "苔藓绿",
  charcoal: "炭灰色",
  terracotta: "陶土色",
  "warm white": "暖白",
  "curved sofa": "弧形沙发",
  "low coffee table": "低矮茶几",
  "built-in storage": "定制收纳",
  "accent chair": "单椅",
  "dining pendant": "餐厅吊灯",
  console: "玄关台",
  "soft daylight": "柔和日光",
  "warm indirect light": "暖色间接光",
  "wall washer": "洗墙灯",
  "cove lighting": "灯槽照明",
  "retail spotlight": "零售射灯",
  "2D color plan": "2D 彩色平面图",
  "3D bird-view": "3D 鸟瞰图",
  "Image generation": "图片生成",
  "Image editing": "图片编辑",
  "Multi-image composition": "多图组合",
  Inpaint: "局部重绘",
  Upscale: "放大增强",
  "text_to_image": "文生图",
  "image_to_image": "图生图",
  "multi_image_composition": "多图组合",
  inpaint: "局部重绘",
  upscale: "放大增强",
  "OpenAI-Compatible Relay": "OpenAI 兼容中转",
  "Zhipu GLM Mainland": "智谱 GLM（中国大陆）",
  "Z.AI International": "Z.AI GLM（国际/海外）",
  "OpenAI-Compatible Custom": "OpenAI 兼容自定义",
  "Custom REST Provider": "自定义 REST 供应商",
  "Volcengine Ark": "火山方舟",
  direct_api: "原生 API",
  relay_base_url: "Base URL 中转",
  native: "原生接口",
  openai_compatible: "OpenAI 兼容",
  gemini_compatible: "Gemini 兼容",
  custom_rest: "自定义 REST",
  connected: "已连接",
  missing_config: "缺少配置",
  missing_base_url: "缺少 Base URL",
  missing_api_key: "缺少 API Key",
  requires_base_url: "需要 Base URL",
  requires_api_key: "需要 API Key",
  invalid_base_url: "Base URL 无效",
  invalid_request: "请求无效",
  auth_error: "认证失败",
  network_error: "网络错误",
  provider_error: "供应商错误",
  response_parse_error: "返回解析失败",
  unsupported_model: "模型不支持",
  model_lookup_unavailable: "待真实出图验证",
  unsupported_auth: "认证方式暂未支持",
  unsupported_consumer_app: "消费版账号不支持 API",
  cost_risk_skipped: "已跳过计费测试",
  skipped_cost_risk: "已跳过计费测试",
  invalid_secret_placeholder: "密钥是占位内容",
  invalid_secret_format: "密钥格式无效",
  invalid_header_value: "Header 格式无效",
  timeout: "超时",
  unauthorized: "认证失败",
  "Relay Text Smoke Test": "中转文本连通性测试",
  "Qigou Board Composer": "栖构方案板编排器",
  "HavenFrame Board Composer": "栖构方案板编排器",
  "Unknown provider": "未知供应商",
};

export function zhLabel(value?: string | null): string {
  if (!value) return "";
  return labelMap[value] ?? value;
}

export function zhList(value?: string | null): string {
  if (!value) return "";
  return value
    .split(",")
    .map((item) => zhLabel(item.trim()))
    .filter(Boolean)
    .join(", ");
}

export function zhOptionLabel<T extends { label: string; value?: string }>(option: T): T {
  return { ...option, label: zhLabel(option.label) };
}

const englishLabelMap: Record<string, string> = {
  房间改造: "Room Renovation", 图片生成: "Image Generation", 方案板生成: "Board Generation",
  风格与配色: "Style and Color", 材质与饰面: "Materials and Finishes", 指定家具: "Selected Furniture", 灯光与氛围: "Lighting and Atmosphere",
  工作台: "Dashboard", 项目: "Projects", 平面图: "Floor Plan", 方案板: "Board",
  "2D 彩色平面图": "2D Color Floor Plan", "3D 鸟瞰图": "3D Bird's-Eye View",
  单房间方案板: "Single-Room Board", 多房间方案板: "Multi-Room Board", 空间渲染: "Space Rendering",
  图片编辑: "Image Editing", 自定义任务: "Custom Tasks", 平面图渲染: "Floor-plan Rendering",
  单房间方案板生成: "Single-Room Board Generation", 多房间方案板生成: "Multi-Room Board Generation",
  自定义任务生成: "Custom Task Generation", 模型连接测试: "Model Connection Test",
  真实模型输出: "Provider Output", 方案板预览: "Board Preview", 渲染输出: "Rendering Output",
  方案板输出: "Board Output", 文本连通性测试: "Text Connection Test", 提取元素: "Extract Items",
  排队中: "Queued", 运行中: "Running", 成功: "Success", 失败: "Failed", 已取消: "Cancelled",
  进行中: "Active", 复盘中: "In Review", 已归档: "Archived", 保留: "Keep", 替换: "Replace",
  删除: "Remove", 待定: "Pending", 客厅: "Living Room", 休闲区: "Lounge", 房间: "Room",
  餐厅: "Dining Room", 卧室: "Bedroom", 厨房: "Kitchen", 卫生间: "Bathroom", 书房: "Study",
  玄关: "Entryway", 零售空间: "Retail", 餐厅空间: "Restaurant", 酒店大堂: "Hotel Lobby",
  展厅: "Showroom", 自定义: "Custom", 现代: "Modern", 极简: "Minimal", 柔和极简: "Soft Minimal",
  侘寂日式: "Japandi", 柔和侘寂: "Soft Japandi", 北欧: "Scandinavian", 侘寂: "Wabi-sabi",
  当代: "Contemporary", 当代轻奢: "Contemporary Luxury", 现代古典: "Modern Classic",
  中古现代: "Mid-century Modern", 工业风: "Industrial", 暖调现代: "Warm Modern", 现代暖调: "Modern Warm",
  自然现代: "Organic Modern", 地中海: "Mediterranean", 法式现代: "French Modern", 装饰艺术: "Art Deco",
  新中式: "Modern Chinese", 禅意: "Zen", 酒店风: "Hospitality Chic", 零售轻奢: "Retail Luxury",
  酒店轻奢: "Luxury Hospitality", 中性极简: "Minimal Neutral", 原生接口: "Native API",
  暖木色: "Warm Wood", 轻奢: "Light Luxury", 大堂: "Lobby", 石材: "Stone",
  象牙白: "Ivory", 灰褐色: "Taupe", 黄铜: "Brass", 弧形沙发: "Curved Sofa",
  低矮茶几: "Low Coffee Table", 金色时刻: "Golden Hour", 胡桃木: "Walnut", 羊羔绒: "Boucle",
  橡木: "Oak", 亚麻: "Linen", 暖白: "Warm White", 炭灰点缀: "Charcoal Accents",
  暖色间接光: "Warm Indirect Light", 柔和日光: "Soft Daylight", 窗户位置: "Window Position", 层高: "Ceiling Height",
  软装搭配: "Furnishing Selection", 表面材质: "Surface Materials", 现有窗户: "Existing Windows", 主沙发位置: "Main Sofa Position",
  零散配饰: "Loose Accessories",
  出图线路: "Generation Routes", 元素提取线路: "Extraction Routes",
  单房间提取: "Single-Room Extraction", 多房间提取: "Multi-Room Extraction",
  栖构方案板编排器: "HavenFrame Board Composer",
  "智谱 GLM": "Zhipu GLM", "智谱 GLM（中国大陆）": "Zhipu GLM (Mainland China)",
  "Z.AI GLM（国际/海外）": "Z.AI GLM (International)",
  "GLM-4.5V 多模态": "GLM-4.5V Multimodal", "GLM-4.5V 多模态提取": "GLM-4.5V Multimodal Extraction",
  原始房间图: "Original Room Image", 参考图: "Reference Image", 情绪板: "Mood Board",
  "蒙版 / 区域选择": "Mask / Region Selection", 源图: "Source Image", "蒙版 / 标记区域": "Mask / Marked Region",
  结构变形: "Structural Distortion", 光线差: "Poor Lighting", 过曝: "Overexposure", 杂乱: "Clutter", 文字伪影: "Text Artifacts",
  "OpenAI 兼容": "OpenAI Compatible", "Gemini 兼容": "Gemini Compatible", 已连接: "Connected",
  缺少配置: "Missing Configuration", 缺少供应商: "Missing Provider", 网络错误: "Network Error",
  供应商错误: "Provider Error", 返回解析失败: "Response Parse Error", 模型不支持: "Unsupported Model",
  超时: "Timeout", 认证失败: "Authentication Failed", 未知供应商: "Unknown Provider",
};

export function localeLabel(value: string | null | undefined, locale: "zh-CN" | "en"): string {
  if (!value) return "";
  if (locale === "zh-CN") return zhLabel(value);
  const zh = labelMap[value] ?? value;
  return englishLabelMap[zh] ?? englishLabelMap[value] ?? value.replace(/_/g, " ");
}
